---
title: "SE Data"
author: "Chris Day"
date: "5/14/2020"
output: html_document
---

## Introduction
The ActivitySim Model requires an input of specific socioeconomic (SE) data on certain counties in the Wasatch Front (Weber, Davis, Salt Lake, Utah). This document explains what data is needed, where the data comes from, and how the data is changed into the correct format in order to be processed.

The socioeconomic file needs 42 different inputs that can be described as different column headings. The headings are the following:  

> ##### ZONE, DISTRICT, SD, COUNTY, TOTHH, HHPOP, TOTPOP, EMPRES, SFDU, MFDU, HHINCQ1, HHINCQ2, HHINCQ3, HHINCQ4, TOTACRE, RESACRE, CIACRE, SHPOP62P, TOTEMP, AGE0004, AGE2044, AGE4564, AGE65P, RETEMPN, FPSEMPN, HEREMPN, OTHEMPN, AGREMPN, MWTEMPN, PRKCST, OPRKCST, area_type, HSENROLL, COLLFTE, COLLPTE, TOPOLOGY, TERMINAL, ZERO, hhlds, sftaz, gqpop

The describtion for each column heading can be found at this link: https://github.com/BayAreaMetro/modeling-website/wiki/TazData

***

### Zone
The Zone data is a list of all the TAZs. This list is copied from the 



